name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "bootloader/**"
      - "firmware/**"
    tags:
      - "v*"

env:
  REPO_PATH: ${{ github.workspace }}/wavephoenix
  BOOTLOADER_PATH: ${{ github.workspace }}/wavephoenix/bootloader
  FIRMWARE_PATH: ${{ github.workspace }}/wavephoenix/firmware
  GECKO_SDK_PATH: ${{ github.workspace }}/gecko_sdk
  SIMPLICITY_COMMANDER_PATH: ${{ github.workspace }}/commander
  SLC_CLI_PATH: ${{ github.workspace }}/slc_cli

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board:
          - efr32xg22e
          - rf-bm-bg22c3
    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python packages
        run: pip install jinja2 pyyaml numpy scipy

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install GNU Arm Embedded Toolchain
        run: |
          cd /tmp
          wget -nv https://developer.arm.com/-/media/Files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi.tar.xz
          tar -xf arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi.tar.xz

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.REPO_PATH }}

      - name: Download Gecko SDK
        run: |
          wget -nv https://github.com/SiliconLabs/gecko_sdk/releases/download/v4.4.5/gecko-sdk.zip
          unzip -q gecko-sdk.zip -d gecko_sdk

      - name: "Download Simplicity Commander"
        run: |
          wget -nv https://www.silabs.com/documents/login/software/SimplicityCommander-Linux.zip
          unzip -q SimplicityCommander-Linux.zip
          tar -xf SimplicityCommander-Linux/Commander_linux_x86_64_*.tar.bz

      - name: Download SLC-CLI
        run: |
          wget -nv https://www.silabs.com/documents/login/software/slc_cli_linux.zip
          unzip -q slc_cli_linux.zip

      - name: Build bootloader
        run: |
          cd ${{ env.BOOTLOADER_PATH }}
          ${{ env.SLC_CLI_PATH }}/slc signature trust --sdk ${{ env.GECKO_SDK_PATH }}
          ${{ env.SLC_CLI_PATH }}/slc configuration --sdk ${{ env.GECKO_SDK_PATH }}
          ${{ env.SLC_CLI_PATH }}/slc configuration --gcc-toolchain /tmp/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi
          ${{ env.SLC_CLI_PATH }}/slc generate -p bootloader-${{ matrix.board }}.slcp -d bootloader_project -o cmake
          cd bootloader_project/bootloader_cmake
          cmake --workflow --preset project
          cmake --preset project && cmake --build --preset default_config

      - name: Build firmware
        run: |
          export PATH=/tmp/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi/bin:$PATH
          cd ${{ env.FIRMWARE_PATH }}
          cmake --preset ${{ matrix.board }} && cmake --build --preset ${{ matrix.board }}

      - name: Update trunk tag
        if: github.ref == 'refs/heads/main'
        run: |
          cd ${{ env.REPO_PATH }}
          git tag -f trunk
          git push -f origin trunk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rename artifacts
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF_NAME}
          else
            VERSION="trunk"
          fi

          mv ${{ env.BOOTLOADER_PATH }}/bootloader_project/bootloader_cmake/build/default_config/bootloader.hex "wavephoenix-bootloader-${VERSION}-${{ matrix.board }}.hex"
          mv ${{ env.FIRMWARE_PATH }}/build/${{ matrix.board }}/receiver/receiver.hex "wavephoenix-receiver-${VERSION}-${{ matrix.board }}.hex"
          mv ${{ env.FIRMWARE_PATH }}/build/${{ matrix.board }}/receiver/receiver.gbl "wavephoenix-receiver-${VERSION}-${{ matrix.board }}.gbl"

      - name: Upload artifacts to trunk release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            wavephoenix-bootloader-*.hex
            wavephoenix-receiver-*.hex
            wavephoenix-receiver-*.gbl
          tag_name: trunk
          name: Trunk Builds
          body: Automated build from main branch, not guaranteed to be stable.
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts to tagged release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            wavephoenix-bootloader-*.hex
            wavephoenix-receiver-*.hex
            wavephoenix-receiver-*.gbl
          tag_name: ${{ github.ref }}
          name: ${{ github.ref_name }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
